/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountItem: typeof import('./src/components/AccountItem.vue')['default']
    CategoryManageTab: typeof import('./src/components/CategoryManageTab.vue')['default']
    CategoryModal: typeof import('./src/components/CategoryModal.vue')['default']
    DashboardTab: typeof import('./src/components/DashboardTab.vue')['default']
    DataCard: typeof import('./src/components/DataCard.vue')['default']
    ExpenditureChart: typeof import('./src/components/ExpenditureChart.vue')['default']
    IncomeChart: typeof import('./src/components/IncomeChart.vue')['default']
    InterfaceCard: typeof import('./src/components/InterfaceCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingTab: typeof import('./src/components/SettingTab.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SideBarTab: typeof import('./src/components/SideBarTab.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    TransactionItem: typeof import('./src/components/TransactionItem.vue')['default']
    TransactionModal: typeof import('./src/components/TransactionModal.vue')['default']
    TransactionsTab: typeof import('./src/components/TransactionsTab.vue')['default']
    TranscationGroup: typeof import('./src/components/TranscationGroup.vue')['default']
    UButton: typeof import('./src/components/UButton.vue')['default']
    UConfirm: typeof import('./src/components/UConfirm.vue')['default']
    UDatePicker: typeof import('./src/components/UDatePicker.vue')['default']
    UInput: typeof import('./src/components/UInput.vue')['default']
    UModal: typeof import('./src/components/UModal.vue')['default']
    USelector: typeof import('./src/components/USelector.vue')['default']
    USnakebar: typeof import('./src/components/USnakebar.vue')['default']
    UTag: typeof import('./src/components/UTag.vue')['default']
  }
}
